# Generated by Django 2.2.16 on 2021-08-31 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playbook',
            old_name='funcName',
            new_name='func_name',
        ),
        migrations.RenameField(
            model_name='playbook',
            old_name='nickName',
            new_name='nick_name',
        ),
    ]
